### This is a chunk of codes for 
### 2021 RNA-seq : Tfh cells Sung prepared for test
### 
#####################################
setwd('~/Desktop/HMH/')
library(dplyr)
library(ggplot2)
library(DESeq2)
library(edgeR)
library(reshape)
### raw data were generated by featurecounts
### read raw counts and save in rds format
list.files('rds/RNA_seq_featurecounts/2021.Tfh.AYAA/features_matrix', full.names = T)
feature_list <- list.files('rds/RNA_seq_featurecounts/2021.Tfh.AYAA/features_matrix', 
                           full.names = T, pattern = 'matrix.txt')
feature_list
feature_list[grep(day,feature_list)]

day <- 'd5'
for(i in 1:6){
  sample <- substr(feature_list[grep(day,feature_list)][i],57,62)
  tmp <- read.table(feature_list[grep(day,feature_list)][i],
                    header = T, col.names = c('gene',paste0(sample,'.count')))
  assign(sample,tmp)
}
day <- 'd9'
for(i in 1:6){
  sample <- substr(feature_list[grep(day,feature_list)][i],57,62)
  tmp <- read.table(feature_list[grep(day,feature_list)][i],
                    header = T, col.names = c('gene',paste0(sample,'.count')))
  assign(sample,tmp)
}


raw.counts <- cbind(d5.wt1,d5.wt2,d5.wt3,d5.mt1,d5.mt2,d5.mt3,
                    d9.wt1,d9.wt2,d9.wt3,d9.mt1,d9.mt2,d9.mt3)
#raw.counts <- cbind(d5.wt1,d5.wt2,d5.wt3,d5.mt1,d5.mt2,d5.mt3)

raw.counts <- raw.counts[c(1,grep('.count', colnames(raw.counts)))]
rownames(raw.counts) <- raw.counts$gene
raw.counts <- raw.counts[,-1]

raw.counts %>% head(30)
raw.counts[c('Tcf7','Icos','Ctla4'),]

write.csv(raw.counts, 'rds/RNA_seq/Tfh_AYAA/Tfh_AYAA.raw.count.2021.11.15.csv')

raw.counts %>% dim()

### filtering 
table(rowSums(raw.counts) == 0)
raw.counts <- raw.counts[rowSums(raw.counts) != 0,]
raw.counts %>% dim()

summary(rowSums(raw.counts))
boxplot(rowSums(raw.counts)) ## outliers : 
hist((rowSums(raw.counts)), breaks = 1000)

raw.counts[rowSums(raw.counts) >= 1e7,] # 1e7
which(rowSums(raw.counts) >= 1e7)
raw.counts <- raw.counts[-which(rowSums(raw.counts) >= 1e7)[[1]],]

raw.counts %>% dim()

raw.counts[rowSums(raw.counts) >= 5e6,] # Actb, Tmsb4x

write.csv(raw.counts, 'rds/RNA_seq/Tfh_AYAA/Tfh_AYAA.raw.count.2021.11.15.csv')

raw.counts %>% head(30)

### filter 2 over 3 in any conditions
tmp <- raw.counts !=0
tmp
f1 <- tmp[tmp[,grep('d5.wt', colnames(tmp))] %>% rowSums() >=2,] %>% rownames()
f2 <- tmp[tmp[,grep('d5.mt', colnames(tmp))] %>% rowSums() >=2,] %>% rownames()
f3 <- tmp[tmp[,grep('d9.wt', colnames(tmp))] %>% rowSums() >=2,] %>% rownames()
f4 <- tmp[tmp[,grep('d9.mt', colnames(tmp))] %>% rowSums() >=2,] %>% rownames()
union(f1,f2) %>% length()
union(union(f1,f2),f3) %>% length()
union(union(union(f1,f2),f3),f4) %>% length()

raw.counts.filtered <- raw.counts[union(union(union(f1,f2),f3),f4),]
raw.counts.filtered %>% head()
write.csv(raw.counts.filtered, 'rds/RNA_seq/Tfh_AYAA/Tfh_AYAA.raw.count.2over3.2021.11.15.csv')




count.mtx <- raw.counts.filtered


## input data : info sheet
info <- data.frame(matrix(nrow = ncol(count.mtx), ncol = 4))
colnames(info) <- c('sample', 'cell_type','mutation','day')
info$sample <- substr(colnames(count.mtx),1,6)
info$cell_type <- 'Tfh'
info$mutation <- substr(info$sample,4,5)
info$mutation <- factor(info$mutation, levels = c('wt','mt'))
info$day <- substr(info$sample,1,2)
info$mt_day <- paste0(info$mutation, '_',info$day)
info$mt_day <- factor(info$mt_day , levels = c('wt_d5', 'mt_d5', 'wt_d9','mt_d9'))
info

###############################################
######## total dds : DESeq ####################
dds <- DESeqDataSetFromMatrix(count.mtx, info, ~mt_day)
dds <- DESeq(dds)

### vst for PCA ### 
vsd <- vst(dds,blind=TRUE)
plotPCA(vsd, intgroup="mt_day")
plotPCA(vsd, intgroup="day")
plotPCA(vsd, intgroup="mutation")
# to remove the dependence of the variance on the mean
#plotPCA(vsd, intgroup="mutation")
pcaplot <- plotPCA(vsd, intgroup="mt_day", return=T)  #using the DESEQ2 plotPCA fxn we can
### drawing plot
theme <- theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank(),
               panel.background = element_blank(), 
               axis.line = element_line(colour = "black"))
ggplot(pcaplot, aes(PC1,PC2, shape=mt_day)) + geom_point(size=3, alpha=0.8) + 
  theme + xlab('PC1:34% variance') + ylab('PC2:15% variance')

ggplot(pcaplot, aes(PC1,PC2, shape=mt_day)) + geom_point(size=3, alpha=0.8) + 
  theme + xlab('PC1:34% variance') + ylab('PC2:15% variance') + facet_grid(.~mt_day)


